name: 'BuildLogger'
version: 1.0
main: cappycap.buildlogger.BuildLogger
api-version: '1.19'
commands:
  dataset:
    description: Handle dataset-related operations
    usage: /<command> <help/add/view/paste/stats>